#!/bin/bash
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/admin_activity.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/capability.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/client.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/client_to_capability.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/client_to_mimetype.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/clubs.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/custom_portlet_mode.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/custom_window_state.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/event_alias.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/event_definition.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/filtered_portlet.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/filter_lifecycle.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/filter_mapping.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/folder.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/folder_constraint.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/folder_constraints_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/folder_menu.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/folder_menu_metadata.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/folder_metadata.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/folder_order.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/jetspeed_service.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/language.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/link.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/link_constraint.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/link_constraints_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/link_metadata.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/locale_encoding_mapping.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/localized_description.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/localized_display_name.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/mediatype_to_capability.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/mediatype_to_mimetype.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/media_type.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/mimetype.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/named_parameter.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_dlist.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_dlist_entries.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_dmap.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_dset.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_dset_entries.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_hl_seq.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_lockentry.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/ojb_nrm.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_constraint.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_constraints_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_menu.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_menu_metadata.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_metadata.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_security.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_sec_constraints_def.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_sec_constraints_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_sec_constraint_def.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/page_statistics.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/fragment.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/fragment_constraint.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/fragment_constraints_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/fragment_pref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/fragment_pref_value.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/fragment_prop.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/parameter.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/parameter_alias.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/pa_metadata_fields.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/pa_security_constraint.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/pd_metadata_fields.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_application.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_definition.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_filter.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_listener.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_preference.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_preference_value.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_statistics.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/portlet_supports.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/principal_permission.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/principal_rule_assoc.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/processing_event.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/profile_page_assoc.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/profiling_rule.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/public_parameter.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/publishing_event.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/rule_criterion.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/runtime_option.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/runtime_value.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/secured_portlet.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_attribute.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_credential.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_domain.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_permission.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_principal.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_principal_assoc.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_role.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/security_role_reference.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/sso_site.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/user_activity.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/user_attribute.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/user_attribute_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/create/user_statistics.sql