#!/bin/bash
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/capability.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/client.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/client_to_capability.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/client_to_mimetype.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/folder.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/folder_constraints_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/folder_menu.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/folder_metadata.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/folder_order.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/jetspeed_service.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/language.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/localized_description.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/localized_display_name.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/mediatype_to_mimetype.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/media_type.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/mimetype.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/ojb_hl_seq.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/page.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/fragment.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/fragment_prop.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/page_constraints_ref.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/page_metadata.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/page_security.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/page_sec_constraints_def.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/page_sec_constraint_def.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/parameter.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/pa_metadata_fields.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/pd_metadata_fields.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/portlet_application.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/portlet_definition.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/portlet_statistics.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/portlet_supports.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/principal_rule_assoc.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/profiling_rule.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/rule_criterion.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/security_domain.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/security_principal.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/security_credential.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/security_permission.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/security_attribute.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/security_principal_assoc.sql
mysql -u$JETSPEED_USER_NAME -p$JETSPEED_PWD $JETSPEED_DATABASE_NAME < $SCRIPT_ROOT_PATH/jetspeed/data/principal_permission.sql
