SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR CAPABILITY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CAPABILITY` (
  `CAPABILITY_ID` DECIMAL(65,30) NOT NULL,
  `CAPABILITY` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`CAPABILITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
