SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR CLIENT_TO_MIMETYPE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CLIENT_TO_MIMETYPE` (
  `CLIENT_ID` DECIMAL(65,30) NOT NULL,
  `MIMETYPE_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`CLIENT_ID`,`MIMETYPE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
