SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR CLIENT_TO_CAPABILITY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CLIENT_TO_CAPABILITY` (
  `CLIENT_ID` DECIMAL(65,30) NOT NULL,
  `CAPABILITY_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`CLIENT_ID`,`CAPABILITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
