SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR CLIENT
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CLIENT` (
  `CLIENT_ID` DECIMAL(65,30) NOT NULL,
  `EVAL_ORDER` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `USER_AGENT_PATTERN` VARCHAR(128) DEFAULT NULL,
  `MANUFACTURER` VARCHAR(80) DEFAULT NULL,
  `MODEL` VARCHAR(80) DEFAULT NULL,
  `VERSION` VARCHAR(40) DEFAULT NULL,
  `PREFERRED_MIMETYPE_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`CLIENT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
