SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR CLUBS
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CLUBS` (
  `NAME` VARCHAR(80) NOT NULL,
  `COUNTRY` VARCHAR(40) NOT NULL,
  `CITY` VARCHAR(40) NOT NULL,
  `STADIUM` VARCHAR(80) NOT NULL,
  `CAPACITY` DECIMAL(65,30) DEFAULT NULL,
  `FOUNDED` DECIMAL(65,30) DEFAULT NULL,
  `PITCH` VARCHAR(40) DEFAULT NULL,
  `NICKNAME` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
