SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR CUSTOM_WINDOW_STATE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `CUSTOM_WINDOW_STATE` (
  `ID` DECIMAL(65,30) NOT NULL,
  `APPLICATION_ID` DECIMAL(65,30) NOT NULL,
  `CUSTOM_NAME` VARCHAR(150) NOT NULL,
  `MAPPED_NAME` VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
