SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR EVENT_DEFINITION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `EVENT_DEFINITION` (
  `ID` DECIMAL(65,30) NOT NULL,
  `APPLICATION_ID` DECIMAL(65,30) NOT NULL,
  `LOCAL_PART` VARCHAR(80) NOT NULL,
  `NAMESPACE` VARCHAR(80) DEFAULT NULL,
  `PREFIX` VARCHAR(20) DEFAULT NULL,
  `VALUE_TYPE` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
