SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FOLDER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FOLDER` (
  `FOLDER_ID` DECIMAL(65,30) NOT NULL,
  `PARENT_ID` DECIMAL(65,30) DEFAULT NULL,
  `PATH` VARCHAR(240) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `TITLE` VARCHAR(100) DEFAULT NULL,
  `SHORT_TITLE` VARCHAR(40) DEFAULT NULL,
  `IS_HIDDEN` DECIMAL(3,0) NOT NULL,
  `SKIN` VARCHAR(80) DEFAULT NULL,
  `DEFAULT_LAYOUT_DECORATOR` VARCHAR(80) DEFAULT NULL,
  `DEFAULT_PORTLET_DECORATOR` VARCHAR(80) DEFAULT NULL,
  `DEFAULT_PAGE_NAME` VARCHAR(80) DEFAULT NULL,
  `SUBSITE` VARCHAR(40) DEFAULT NULL,
  `USER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `ROLE_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `GROUP_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `MEDIATYPE` VARCHAR(15) DEFAULT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `EXT_ATTR_NAME` VARCHAR(15) DEFAULT NULL,
  `EXT_ATTR_VALUE` VARCHAR(40) DEFAULT NULL,
  `OWNER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`FOLDER_ID`),
  UNIQUE KEY `UN_FOLDER_1` (`PATH`) USING BTREE,
  KEY `IX_FOLDER_1` (`PARENT_ID`) USING BTREE,
  CONSTRAINT `FOLDER_IBFK_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `FOLDER` (`FOLDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
