SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FOLDER_MENU_METADATA
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FOLDER_MENU_METADATA` (
  `METADATA_ID` DECIMAL(65,30) NOT NULL,
  `MENU_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(15) NOT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`METADATA_ID`),
  UNIQUE KEY `UN_FOLDER_MENU_METADATA_1` (`MENU_ID`,`NAME`,`LOCALE`,`VALUE`) USING BTREE,
  KEY `IX_FOLDER_MENU_METADATA_1` (`MENU_ID`) USING BTREE,
  CONSTRAINT `FOLDER_MENU_METADATA_IBFK_1` FOREIGN KEY (`MENU_ID`) REFERENCES `FOLDER_MENU` (`MENU_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
