SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FOLDER_ORDER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FOLDER_ORDER` (
  `ORDER_ID` DECIMAL(65,30) NOT NULL,
  `FOLDER_ID` DECIMAL(65,30) NOT NULL,
  `SORT_ORDER` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  UNIQUE KEY `UN_FOLDER_ORDER_1` (`FOLDER_ID`,`NAME`) USING BTREE,
  KEY `IX_FOLDER_ORDER_1` (`FOLDER_ID`) USING BTREE,
  CONSTRAINT `FOLDER_ORDER_IBFK_1` FOREIGN KEY (`FOLDER_ID`) REFERENCES `FOLDER` (`FOLDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
