SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FOLDER_METADATA
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FOLDER_METADATA` (
  `METADATA_ID` DECIMAL(65,30) NOT NULL,
  `FOLDER_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(15) NOT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`METADATA_ID`),
  UNIQUE KEY `UN_FOLDER_METADATA_1` (`FOLDER_ID`,`NAME`,`LOCALE`,`VALUE`) USING BTREE,
  KEY `IX_FOLDER_METADATA_1` (`FOLDER_ID`) USING BTREE,
  CONSTRAINT `FOLDER_METADATA_IBFK_1` FOREIGN KEY (`FOLDER_ID`) REFERENCES `FOLDER` (`FOLDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
