SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FRAGMENT_PREF
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FRAGMENT_PREF` (
  `PREF_ID` DECIMAL(65,30) NOT NULL,
  `FRAGMENT_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  `IS_READ_ONLY` DECIMAL(3,0) NOT NULL,
  PRIMARY KEY (`PREF_ID`),
  UNIQUE KEY `UN_FRAGMENT_PREF_1` (`FRAGMENT_ID`,`NAME`) USING BTREE,
  KEY `IX_FRAGMENT_PREF_1` (`FRAGMENT_ID`) USING BTREE,
  CONSTRAINT `FRAGMENT_PREF_IBFK_1` FOREIGN KEY (`FRAGMENT_ID`) REFERENCES `FRAGMENT` (`FRAGMENT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
