SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FRAGMENT_PROP
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FRAGMENT_PROP` (
  `PROP_ID` DECIMAL(65,30) NOT NULL,
  `FRAGMENT_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  `SCOPE` VARCHAR(10) DEFAULT NULL,
  `SCOPE_VALUE` VARCHAR(40) DEFAULT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PROP_ID`),
  UNIQUE KEY `UN_FRAGMENT_PROP_1` (`FRAGMENT_ID`,`NAME`,`SCOPE`,`SCOPE_VALUE`) USING BTREE,
  KEY `IX_FRAGMENT_PROP_1` (`FRAGMENT_ID`) USING BTREE,
  CONSTRAINT `FRAGMENT_PROP_IBFK_1` FOREIGN KEY (`FRAGMENT_ID`) REFERENCES `FRAGMENT` (`FRAGMENT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
