SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FRAGMENT_PREF_VALUE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FRAGMENT_PREF_VALUE` (
  `PREF_VALUE_ID` DECIMAL(65,30) NOT NULL,
  `PREF_ID` DECIMAL(65,30) NOT NULL,
  `VALUE_ORDER` DECIMAL(65,30) NOT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PREF_VALUE_ID`),
  KEY `IX_FRAGMENT_PREF_VALUE_1` (`PREF_ID`) USING BTREE,
  CONSTRAINT `FRAGMENT_PREF_VALUE_IBFK_1` FOREIGN KEY (`PREF_ID`) REFERENCES `FRAGMENT_PREF` (`PREF_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
