SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FRAGMENT
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FRAGMENT` (
  `FRAGMENT_ID` DECIMAL(65,30) NOT NULL,
  `CLASS_NAME` VARCHAR(100) NOT NULL,
  `PARENT_ID` DECIMAL(65,30) DEFAULT NULL,
  `PAGE_ID` DECIMAL(65,30) DEFAULT NULL,
  `FRAGMENT_STRING_ID` VARCHAR(80) DEFAULT NULL,
  `FRAGMENT_STRING_REFID` VARCHAR(80) DEFAULT NULL,
  `NAME` VARCHAR(100) DEFAULT NULL,
  `TITLE` VARCHAR(100) DEFAULT NULL,
  `SHORT_TITLE` VARCHAR(40) DEFAULT NULL,
  `TYPE` VARCHAR(40) DEFAULT NULL,
  `SKIN` VARCHAR(80) DEFAULT NULL,
  `DECORATOR` VARCHAR(80) DEFAULT NULL,
  `STATE` VARCHAR(10) DEFAULT NULL,
  `PMODE` VARCHAR(10) DEFAULT NULL,
  `LAYOUT_ROW` DECIMAL(65,30) DEFAULT NULL,
  `LAYOUT_COLUMN` DECIMAL(65,30) DEFAULT NULL,
  `LAYOUT_SIZES` VARCHAR(20) DEFAULT NULL,
  `LAYOUT_X` DOUBLE DEFAULT NULL,
  `LAYOUT_Y` DOUBLE DEFAULT NULL,
  `LAYOUT_Z` DOUBLE DEFAULT NULL,
  `LAYOUT_WIDTH` DOUBLE DEFAULT NULL,
  `LAYOUT_HEIGHT` DOUBLE DEFAULT NULL,
  `OWNER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`FRAGMENT_ID`),
  KEY `IX_FRAGMENT_1` (`PARENT_ID`) USING BTREE,
  KEY `IX_FRAGMENT_2` (`FRAGMENT_STRING_REFID`) USING BTREE,
  KEY `IX_FRAGMENT_3` (`FRAGMENT_STRING_ID`) USING BTREE,
  KEY `UN_FRAGMENT_1` (`PAGE_ID`) USING BTREE,
  CONSTRAINT `FRAGMENT_IBFK_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `FRAGMENT` (`FRAGMENT_ID`),
  CONSTRAINT `FRAGMENT_IBFK_2` FOREIGN KEY (`PAGE_ID`) REFERENCES `PAGE` (`PAGE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
