SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR FRAGMENT_CONSTRAINTS_REF
-- ----------------------------
CREATE TABLE IF NOT EXISTS `FRAGMENT_CONSTRAINTS_REF` (
  `CONSTRAINTS_REF_ID` DECIMAL(65,30) NOT NULL,
  `FRAGMENT_ID` DECIMAL(65,30) NOT NULL,
  `APPLY_ORDER` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`CONSTRAINTS_REF_ID`),
  UNIQUE KEY `UN_FRAGMENT_CONSTRAINTS_REF_1` (`FRAGMENT_ID`,`NAME`) USING BTREE,
  KEY `IX_FRAGMENT_CONSTRAINTS_REF_1` (`FRAGMENT_ID`) USING BTREE,
  CONSTRAINT `FRAGMENT_CONSTRAINTS_REF_IBFK_1` FOREIGN KEY (`FRAGMENT_ID`) REFERENCES `FRAGMENT` (`FRAGMENT_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
