SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR LANGUAGE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `LANGUAGE` (
  `ID` DECIMAL(65,30) NOT NULL,
  `PORTLET_ID` DECIMAL(65,30) NOT NULL,
  `LOCALE_STRING` VARCHAR(50) NOT NULL,
  `SUPPORTED_LOCALE` DECIMAL(3,0) NOT NULL,
  `TITLE` VARCHAR(100) DEFAULT NULL,
  `SHORT_TITLE` VARCHAR(100) DEFAULT NULL,
  `KEYWORDS` TEXT,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
