SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR LINK
-- ----------------------------
CREATE TABLE IF NOT EXISTS `LINK` (
  `LINK_ID` DECIMAL(65,30) NOT NULL,
  `PARENT_ID` DECIMAL(65,30) NOT NULL,
  `PATH` VARCHAR(240) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `VERSION` VARCHAR(40) DEFAULT NULL,
  `TITLE` VARCHAR(100) DEFAULT NULL,
  `SHORT_TITLE` VARCHAR(40) DEFAULT NULL,
  `IS_HIDDEN` DECIMAL(3,0) NOT NULL,
  `SKIN` VARCHAR(80) DEFAULT NULL,
  `TARGET` VARCHAR(80) DEFAULT NULL,
  `URL` VARCHAR(255) DEFAULT NULL,
  `SUBSITE` VARCHAR(40) DEFAULT NULL,
  `USER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `ROLE_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `GROUP_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `MEDIATYPE` VARCHAR(15) DEFAULT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `EXT_ATTR_NAME` VARCHAR(15) DEFAULT NULL,
  `EXT_ATTR_VALUE` VARCHAR(40) DEFAULT NULL,
  `OWNER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`LINK_ID`),
  UNIQUE KEY `UN_LINK_1` (`PATH`) USING BTREE,
  KEY `IX_LINK_1` (`PARENT_ID`) USING BTREE,
  CONSTRAINT `LINK_IBFK_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `FOLDER` (`FOLDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
