SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR LINK_METADATA
-- ----------------------------
CREATE TABLE IF NOT EXISTS `LINK_METADATA` (
  `METADATA_ID` DECIMAL(65,30) NOT NULL,
  `LINK_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(15) NOT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`METADATA_ID`),
  UNIQUE KEY `UN_LINK_METADATA_1` (`LINK_ID`,`NAME`,`LOCALE`,`VALUE`) USING BTREE,
  KEY `IX_LINK_METADATA_1` (`LINK_ID`) USING BTREE,
  CONSTRAINT `LINK_METADATA_IBFK_1` FOREIGN KEY (`LINK_ID`) REFERENCES `LINK` (`LINK_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
