SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR LINK_CONSTRAINTS_REF
-- ----------------------------
CREATE TABLE IF NOT EXISTS `LINK_CONSTRAINTS_REF` (
  `CONSTRAINTS_REF_ID` DECIMAL(65,30) NOT NULL,
  `LINK_ID` DECIMAL(65,30) NOT NULL,
  `APPLY_ORDER` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`CONSTRAINTS_REF_ID`),
  UNIQUE KEY `UN_LINK_CONSTRAINTS_REF_1` (`LINK_ID`,`NAME`) USING BTREE,
  KEY `IX_LINK_CONSTRAINTS_REF_1` (`LINK_ID`) USING BTREE,
  CONSTRAINT `LINK_CONSTRAINTS_REF_IBFK_1` FOREIGN KEY (`LINK_ID`) REFERENCES `LINK` (`LINK_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
