SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR LOCALIZED_DESCRIPTION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `LOCALIZED_DESCRIPTION` (
  `ID` DECIMAL(65,30) NOT NULL,
  `OWNER_ID` DECIMAL(65,30) NOT NULL,
  `OWNER_CLASS_NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` TEXT NOT NULL,
  `LOCALE_STRING` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
