SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR MEDIATYPE_TO_MIMETYPE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `MEDIATYPE_TO_MIMETYPE` (
  `MEDIATYPE_ID` DECIMAL(65,30) NOT NULL,
  `MIMETYPE_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`MEDIATYPE_ID`,`MIMETYPE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
