SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR MEDIATYPE_TO_CAPABILITY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `MEDIATYPE_TO_CAPABILITY` (
  `MEDIATYPE_ID` DECIMAL(65,30) NOT NULL,
  `CAPABILITY_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`MEDIATYPE_ID`,`CAPABILITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
