SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR MEDIA_TYPE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `MEDIA_TYPE` (
  `MEDIATYPE_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `CHARACTER_SET` VARCHAR(40) DEFAULT NULL,
  `TITLE` VARCHAR(80) DEFAULT NULL,
  `DESCRIPTION` TEXT,
  PRIMARY KEY (`MEDIATYPE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
