SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR MIMETYPE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `MIMETYPE` (
  `MIMETYPE_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`MIMETYPE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
