SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR NAMED_PARAMETER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `NAMED_PARAMETER` (
  `ID` DECIMAL(65,30) NOT NULL,
  `OWNER_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
