SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR OJB_NRM
-- ----------------------------
CREATE TABLE IF NOT EXISTS `OJB_NRM` (
  `NAME` VARCHAR(250) NOT NULL,
  `OID_` LONGBLOB,
  PRIMARY KEY (`NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
