SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR OJB_DSET
-- ----------------------------
CREATE TABLE IF NOT EXISTS `OJB_DSET` (
  `ID` DECIMAL(65,30) NOT NULL,
  `SIZE_` DECIMAL(65,30) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
