SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PAGE_SECURITY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PAGE_SECURITY` (
  `PAGE_SECURITY_ID` DECIMAL(65,30) NOT NULL,
  `PARENT_ID` DECIMAL(65,30) NOT NULL,
  `PATH` VARCHAR(240) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `VERSION` VARCHAR(40) DEFAULT NULL,
  `SUBSITE` VARCHAR(40) DEFAULT NULL,
  `USER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `ROLE_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `GROUP_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `MEDIATYPE` VARCHAR(15) DEFAULT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `EXT_ATTR_NAME` VARCHAR(15) DEFAULT NULL,
  `EXT_ATTR_VALUE` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`PAGE_SECURITY_ID`),
  UNIQUE KEY `UN_PAGE_SECURITY_1` (`PARENT_ID`) USING BTREE,
  UNIQUE KEY `UN_PAGE_SECURITY_2` (`PATH`) USING BTREE,
  CONSTRAINT `PAGE_SECURITY_IBFK_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `FOLDER` (`FOLDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
