SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PAGE_METADATA
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PAGE_METADATA` (
  `METADATA_ID` DECIMAL(65,30) NOT NULL,
  `PAGE_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(15) NOT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `VALUE` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`METADATA_ID`),
  UNIQUE KEY `UN_PAGE_METADATA_1` (`PAGE_ID`,`NAME`,`LOCALE`,`VALUE`) USING BTREE,
  KEY `IX_PAGE_METADATA_1` (`PAGE_ID`) USING BTREE,
  CONSTRAINT `PAGE_METADATA_IBFK_1` FOREIGN KEY (`PAGE_ID`) REFERENCES `PAGE` (`PAGE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
