SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PAGE_SEC_CONSTRAINTS_DEF
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PAGE_SEC_CONSTRAINTS_DEF` (
  `CONSTRAINTS_DEF_ID` DECIMAL(65,30) NOT NULL,
  `PAGE_SECURITY_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`CONSTRAINTS_DEF_ID`),
  UNIQUE KEY `UN_PAGE_SEC_CONSTRAINTS_DEF_1` (`PAGE_SECURITY_ID`,`NAME`) USING BTREE,
  KEY `IX_PAGE_SEC_CONSTRAINTS_DEF_1` (`PAGE_SECURITY_ID`) USING BTREE,
  CONSTRAINT `PAGE_SEC_CONSTRAINTS_DEF_IBFK_1` FOREIGN KEY (`PAGE_SECURITY_ID`) REFERENCES `PAGE_SECURITY` (`PAGE_SECURITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
