SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PAGE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PAGE` (
  `PAGE_ID` DECIMAL(65,30) NOT NULL,
  `CLASS_NAME` VARCHAR(100) NOT NULL,
  `PARENT_ID` DECIMAL(65,30) NOT NULL,
  `PATH` VARCHAR(240) NOT NULL,
  `CONTENT_TYPE` VARCHAR(40) DEFAULT NULL,
  `IS_INHERITABLE` DECIMAL(3,0) DEFAULT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `VERSION` VARCHAR(40) DEFAULT NULL,
  `TITLE` VARCHAR(100) DEFAULT NULL,
  `SHORT_TITLE` VARCHAR(40) DEFAULT NULL,
  `IS_HIDDEN` DECIMAL(3,0) DEFAULT NULL,
  `SKIN` VARCHAR(80) DEFAULT NULL,
  `DEFAULT_LAYOUT_DECORATOR` VARCHAR(80) DEFAULT NULL,
  `DEFAULT_PORTLET_DECORATOR` VARCHAR(80) DEFAULT NULL,
  `SUBSITE` VARCHAR(40) DEFAULT NULL,
  `USER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `ROLE_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `GROUP_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  `MEDIATYPE` VARCHAR(15) DEFAULT NULL,
  `LOCALE` VARCHAR(20) DEFAULT NULL,
  `EXT_ATTR_NAME` VARCHAR(15) DEFAULT NULL,
  `EXT_ATTR_VALUE` VARCHAR(40) DEFAULT NULL,
  `OWNER_PRINCIPAL` VARCHAR(40) DEFAULT NULL,
  PRIMARY KEY (`PAGE_ID`),
  UNIQUE KEY `UN_PAGE_1` (`PATH`) USING BTREE,
  KEY `IX_PAGE_1` (`PARENT_ID`) USING BTREE,
  CONSTRAINT `PAGE_IBFK_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `FOLDER` (`FOLDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
