SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PAGE_SEC_CONSTRAINT_DEF
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PAGE_SEC_CONSTRAINT_DEF` (
  `CONSTRAINT_DEF_ID` DECIMAL(65,30) NOT NULL,
  `CONSTRAINTS_DEF_ID` DECIMAL(65,30) NOT NULL,
  `APPLY_ORDER` DECIMAL(65,30) NOT NULL,
  `USER_PRINCIPALS_ACL` VARCHAR(120) DEFAULT NULL,
  `ROLE_PRINCIPALS_ACL` VARCHAR(120) DEFAULT NULL,
  `GROUP_PRINCIPALS_ACL` VARCHAR(120) DEFAULT NULL,
  `PERMISSIONS_ACL` VARCHAR(120) DEFAULT NULL,
  PRIMARY KEY (`CONSTRAINT_DEF_ID`),
  KEY `IX_PAGE_SEC_CONSTRAINT_DEF_1` (`CONSTRAINTS_DEF_ID`) USING BTREE,
  CONSTRAINT `PAGE_SEC_CONSTRAINT_DEF_IBFK_1` FOREIGN KEY (`CONSTRAINTS_DEF_ID`) REFERENCES `PAGE_SEC_CONSTRAINTS_DEF` (`CONSTRAINTS_DEF_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
