SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PAGE_CONSTRAINT
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PAGE_CONSTRAINT` (
  `CONSTRAINT_ID` DECIMAL(65,30) NOT NULL,
  `PAGE_ID` DECIMAL(65,30) NOT NULL,
  `APPLY_ORDER` DECIMAL(65,30) NOT NULL,
  `USER_PRINCIPALS_ACL` VARCHAR(120) DEFAULT NULL,
  `ROLE_PRINCIPALS_ACL` VARCHAR(120) DEFAULT NULL,
  `GROUP_PRINCIPALS_ACL` VARCHAR(120) DEFAULT NULL,
  `PERMISSIONS_ACL` VARCHAR(120) DEFAULT NULL,
  PRIMARY KEY (`CONSTRAINT_ID`),
  KEY `IX_PAGE_CONSTRAINT_1` (`PAGE_ID`) USING BTREE,
  CONSTRAINT `PAGE_CONSTRAINT_IBFK_1` FOREIGN KEY (`PAGE_ID`) REFERENCES `PAGE` (`PAGE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
