SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PAGE_SEC_CONSTRAINTS_REF
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PAGE_SEC_CONSTRAINTS_REF` (
  `CONSTRAINTS_REF_ID` DECIMAL(65,30) NOT NULL,
  `PAGE_SECURITY_ID` DECIMAL(65,30) NOT NULL,
  `APPLY_ORDER` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`CONSTRAINTS_REF_ID`),
  UNIQUE KEY `UN_PAGE_SEC_CONSTRAINTS_REF_1` (`PAGE_SECURITY_ID`,`NAME`) USING BTREE,
  KEY `IX_PAGE_SEC_CONSTRAINTS_REF_1` (`PAGE_SECURITY_ID`) USING BTREE,
  CONSTRAINT `PAGE_SEC_CONSTRAINTS_REF_IBFK_1` FOREIGN KEY (`PAGE_SECURITY_ID`) REFERENCES `PAGE_SECURITY` (`PAGE_SECURITY_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
