SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PARAMETER_ALIAS
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PARAMETER_ALIAS` (
  `ID` DECIMAL(65,30) NOT NULL,
  `OWNER_ID` DECIMAL(65,30) NOT NULL,
  `LOCAL_PART` VARCHAR(80) NOT NULL,
  `NAMESPACE` VARCHAR(80) DEFAULT NULL,
  `PREFIX` VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
