SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PARAMETER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PARAMETER` (
  `PARAMETER_ID` DECIMAL(65,30) NOT NULL,
  `OWNER_ID` DECIMAL(65,30) NOT NULL,
  `OWNER_CLASS_NAME` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `PARAMETER_VALUE` TEXT,
  PRIMARY KEY (`PARAMETER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
