SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PD_METADATA_FIELDS
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PD_METADATA_FIELDS` (
  `ID` DECIMAL(65,30) NOT NULL,
  `OBJECT_ID` DECIMAL(65,30) NOT NULL,
  `COLUMN_VALUE` TEXT NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `LOCALE_STRING` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
