SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PORTLET_APPLICATION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PORTLET_APPLICATION` (
  `APPLICATION_ID` DECIMAL(65,30) NOT NULL,
  `APP_NAME` VARCHAR(80) NOT NULL,
  `CONTEXT_PATH` VARCHAR(255) NOT NULL,
  `REVISION` DECIMAL(65,30) NOT NULL,
  `VERSION` VARCHAR(80) DEFAULT NULL,
  `APP_TYPE` DECIMAL(65,30) DEFAULT NULL,
  `CHECKSUM` VARCHAR(80) DEFAULT NULL,
  `SECURITY_REF` VARCHAR(40) DEFAULT NULL,
  `DEFAULT_NAMESPACE` VARCHAR(120) DEFAULT NULL,
  `RESOURCE_BUNDLE` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`APPLICATION_ID`),
  UNIQUE KEY `UK_APPLICATION` (`APP_NAME`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
