SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PORTLET_FILTER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PORTLET_FILTER` (
  `ID` DECIMAL(65,30) NOT NULL,
  `APPLICATION_ID` DECIMAL(65,30) NOT NULL,
  `FILTER_NAME` VARCHAR(80) NOT NULL,
  `FILTER_CLASS` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
