SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PORTLET_PREFERENCE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PORTLET_PREFERENCE` (
  `ID` DECIMAL(65,30) NOT NULL,
  `DTYPE` VARCHAR(10) NOT NULL,
  `APPLICATION_NAME` VARCHAR(80) NOT NULL,
  `PORTLET_NAME` VARCHAR(80) NOT NULL,
  `ENTITY_ID` VARCHAR(80) DEFAULT NULL,
  `USER_NAME` VARCHAR(80) DEFAULT NULL,
  `NAME` VARCHAR(254) NOT NULL,
  `READONLY` DECIMAL(3,0) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UIX_PORTLET_PREFERENCE` (`DTYPE`,`APPLICATION_NAME`,`PORTLET_NAME`,`ENTITY_ID`,`USER_NAME`,`NAME`) USING BTREE,
  KEY `IX_USER_PREFERENCE` (`DTYPE`,`USER_NAME`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
