SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PORTLET_SUPPORTS
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PORTLET_SUPPORTS` (
  `SUPPORTS_ID` DECIMAL(65,30) NOT NULL,
  `PORTLET_ID` DECIMAL(65,30) NOT NULL,
  `MIME_TYPE` VARCHAR(30) NOT NULL,
  `MODES` VARCHAR(255) DEFAULT NULL,
  `STATES` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`SUPPORTS_ID`),
  UNIQUE KEY `UK_SUPPORTS` (`PORTLET_ID`,`MIME_TYPE`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
