SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PORTLET_PREFERENCE_VALUE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PORTLET_PREFERENCE_VALUE` (
  `ID` DECIMAL(65,30) NOT NULL,
  `PREF_ID` DECIMAL(65,30) NOT NULL,
  `IDX` DECIMAL(5,0) NOT NULL,
  `PREF_VALUE` TEXT,
  PRIMARY KEY (`ID`,`PREF_ID`,`IDX`),
  KEY `IX_PORTLET_PREFERENCE` (`PREF_ID`) USING BTREE,
  CONSTRAINT `PORTLET_PREFERENCE_VALUE_IBFK_1` FOREIGN KEY (`PREF_ID`) REFERENCES `PORTLET_PREFERENCE` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
