SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PRINCIPAL_PERMISSION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PRINCIPAL_PERMISSION` (
  `PRINCIPAL_ID` DECIMAL(65,30) NOT NULL,
  `PERMISSION_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`,`PERMISSION_ID`),
  KEY `IX_PRINCIPAL_PERMISSION_1` (`PERMISSION_ID`) USING BTREE,
  KEY `IX_PRINCIPAL_PERMISSION_2` (`PRINCIPAL_ID`) USING BTREE,
  CONSTRAINT `PRINCIPAL_PERMISSION_IBFK_1` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `SECURITY_PERMISSION` (`PERMISSION_ID`),
  CONSTRAINT `PRINCIPAL_PERMISSION_IBFK_2` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `SECURITY_PRINCIPAL` (`PRINCIPAL_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
