SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PRINCIPAL_RULE_ASSOC
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PRINCIPAL_RULE_ASSOC` (
  `PRINCIPAL_NAME` VARCHAR(80) NOT NULL,
  `LOCATOR_NAME` VARCHAR(80) NOT NULL,
  `RULE_ID` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`PRINCIPAL_NAME`,`LOCATOR_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
