SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PROFILE_PAGE_ASSOC
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PROFILE_PAGE_ASSOC` (
  `LOCATOR_HASH` VARCHAR(40) NOT NULL,
  `PAGE_ID` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`LOCATOR_HASH`,`PAGE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
