SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PROFILING_RULE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PROFILING_RULE` (
  `RULE_ID` VARCHAR(80) NOT NULL,
  `CLASS_NAME` VARCHAR(100) NOT NULL,
  `TITLE` VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (`RULE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
