SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PUBLIC_PARAMETER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PUBLIC_PARAMETER` (
  `ID` DECIMAL(65,30) NOT NULL,
  `APPLICATION_ID` DECIMAL(65,30) NOT NULL,
  `LOCAL_PART` VARCHAR(80) NOT NULL,
  `NAMESPACE` VARCHAR(80) DEFAULT NULL,
  `PREFIX` VARCHAR(20) DEFAULT NULL,
  `IDENTIFIER` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
