SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR RULE_CRITERION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `RULE_CRITERION` (
  `CRITERION_ID` VARCHAR(80) NOT NULL,
  `RULE_ID` VARCHAR(80) NOT NULL,
  `FALLBACK_ORDER` DECIMAL(65,30) NOT NULL,
  `REQUEST_TYPE` VARCHAR(40) NOT NULL,
  `NAME` VARCHAR(80) NOT NULL,
  `COLUMN_VALUE` VARCHAR(128) DEFAULT NULL,
  `FALLBACK_TYPE` DECIMAL(65,30) DEFAULT NULL,
  PRIMARY KEY (`CRITERION_ID`),
  KEY `IX_RULE_CRITERION_1` (`RULE_ID`) USING BTREE,
  KEY `IX_RULE_CRITERION_2` (`RULE_ID`,`FALLBACK_ORDER`) USING BTREE,
  CONSTRAINT `RULE_CRITERION_IBFK_1` FOREIGN KEY (`RULE_ID`) REFERENCES `PROFILING_RULE` (`RULE_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
