SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR RUNTIME_OPTION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `RUNTIME_OPTION` (
  `ID` DECIMAL(65,30) NOT NULL,
  `OWNER_ID` DECIMAL(65,30) NOT NULL,
  `OWNER_CLASS_NAME` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
