SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR RUNTIME_VALUE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `RUNTIME_VALUE` (
  `ID` DECIMAL(65,30) NOT NULL,
  `OWNER_ID` DECIMAL(65,30) NOT NULL,
  `RVALUE` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
