SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR SECURITY_PRINCIPAL_ASSOC
-- ----------------------------
CREATE TABLE IF NOT EXISTS `SECURITY_PRINCIPAL_ASSOC` (
  `ASSOC_NAME` VARCHAR(30) NOT NULL,
  `FROM_PRINCIPAL_ID` DECIMAL(65,30) NOT NULL,
  `TO_PRINCIPAL_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`ASSOC_NAME`,`FROM_PRINCIPAL_ID`,`TO_PRINCIPAL_ID`),
  KEY `IX_FROM_PRINCIPAL_ASSOC` (`FROM_PRINCIPAL_ID`) USING BTREE,
  KEY `IX_TO_PRINCIPAL_ASSOC` (`TO_PRINCIPAL_ID`) USING BTREE,
  KEY `IX_TO_PRINCIPAL_ASSOC_LOOKUP` (`ASSOC_NAME`,`TO_PRINCIPAL_ID`) USING BTREE,
  CONSTRAINT `SECURITY_PRINCIPAL_ASSOC_IBFK_1` FOREIGN KEY (`FROM_PRINCIPAL_ID`) REFERENCES `SECURITY_PRINCIPAL` (`PRINCIPAL_ID`),
  CONSTRAINT `SECURITY_PRINCIPAL_ASSOC_IBFK_2` FOREIGN KEY (`TO_PRINCIPAL_ID`) REFERENCES `SECURITY_PRINCIPAL` (`PRINCIPAL_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
