SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR SECURITY_CREDENTIAL
-- ----------------------------
CREATE TABLE IF NOT EXISTS `SECURITY_CREDENTIAL` (
  `CREDENTIAL_ID` DECIMAL(65,30) NOT NULL,
  `PRINCIPAL_ID` DECIMAL(65,30) NOT NULL,
  `CREDENTIAL_VALUE` VARCHAR(254) DEFAULT NULL,
  `TYPE` DECIMAL(5,0) NOT NULL,
  `UPDATE_ALLOWED` DECIMAL(3,0) NOT NULL,
  `IS_STATE_READONLY` DECIMAL(3,0) NOT NULL,
  `UPDATE_REQUIRED` DECIMAL(3,0) NOT NULL,
  `IS_ENCODED` DECIMAL(3,0) NOT NULL,
  `IS_ENABLED` DECIMAL(3,0) NOT NULL,
  `AUTH_FAILURES` DECIMAL(5,0) NOT NULL,
  `IS_EXPIRED` DECIMAL(3,0) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFIED_DATE` DATETIME NOT NULL,
  `PREV_AUTH_DATE` DATETIME DEFAULT NULL,
  `LAST_AUTH_DATE` DATETIME DEFAULT NULL,
  `EXPIRATION_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`CREDENTIAL_ID`),
  KEY `IX_SECURITY_CREDENTIAL_1` (`PRINCIPAL_ID`) USING BTREE,
  CONSTRAINT `SECURITY_CREDENTIAL_IBFK_1` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `SECURITY_PRINCIPAL` (`PRINCIPAL_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
