SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR SECURITY_DOMAIN
-- ----------------------------
CREATE TABLE IF NOT EXISTS `SECURITY_DOMAIN` (
  `DOMAIN_ID` DECIMAL(65,30) NOT NULL,
  `DOMAIN_NAME` VARCHAR(254) DEFAULT NULL,
  `REMOTE` DECIMAL(3,0) DEFAULT NULL,
  `ENABLED` DECIMAL(3,0) DEFAULT NULL,
  `OWNER_DOMAIN_ID` DECIMAL(65,30) DEFAULT NULL,
  PRIMARY KEY (`DOMAIN_ID`),
  UNIQUE KEY `UIX_DOMAIN_NAME` (`DOMAIN_NAME`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
