SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR SECURITY_PRINCIPAL
-- ----------------------------
CREATE TABLE IF NOT EXISTS `SECURITY_PRINCIPAL` (
  `PRINCIPAL_ID` DECIMAL(65,30) NOT NULL,
  `PRINCIPAL_TYPE` VARCHAR(20) NOT NULL,
  `PRINCIPAL_NAME` VARCHAR(200) NOT NULL,
  `IS_MAPPED` DECIMAL(3,0) NOT NULL,
  `IS_ENABLED` DECIMAL(3,0) NOT NULL,
  `IS_READONLY` DECIMAL(3,0) NOT NULL,
  `IS_REMOVABLE` DECIMAL(3,0) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFIED_DATE` DATETIME NOT NULL,
  `DOMAIN_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`PRINCIPAL_ID`),
  UNIQUE KEY `UIX_SECURITY_PRINCIPAL` (`PRINCIPAL_TYPE`,`PRINCIPAL_NAME`,`DOMAIN_ID`) USING BTREE,
  KEY `IX_SECURITY_DOMAIN_1` (`DOMAIN_ID`) USING BTREE,
  CONSTRAINT `SECURITY_PRINCIPAL_IBFK_1` FOREIGN KEY (`DOMAIN_ID`) REFERENCES `SECURITY_DOMAIN` (`DOMAIN_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
