SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR SECURITY_ATTRIBUTE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `SECURITY_ATTRIBUTE` (
  `ATTR_ID` DECIMAL(65,30) NOT NULL,
  `PRINCIPAL_ID` DECIMAL(65,30) NOT NULL,
  `ATTR_NAME` VARCHAR(200) NOT NULL,
  `ATTR_VALUE` TEXT,
  PRIMARY KEY (`ATTR_ID`,`PRINCIPAL_ID`,`ATTR_NAME`),
  KEY `IX_NAME_LOOKUP` (`ATTR_NAME`) USING BTREE,
  KEY `IX_PRINCIPAL_ATTR` (`PRINCIPAL_ID`) USING BTREE,
  CONSTRAINT `SECURITY_ATTRIBUTE_IBFK_1` FOREIGN KEY (`PRINCIPAL_ID`) REFERENCES `SECURITY_PRINCIPAL` (`PRINCIPAL_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
