SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR SECURITY_ROLE_REFERENCE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `SECURITY_ROLE_REFERENCE` (
  `ID` DECIMAL(65,30) NOT NULL,
  `PORTLET_DEFINITION_ID` DECIMAL(65,30) NOT NULL,
  `ROLE_NAME` VARCHAR(150) NOT NULL,
  `ROLE_LINK` VARCHAR(150) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
