SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR SSO_SITE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `SSO_SITE` (
  `SITE_ID` DECIMAL(65,30) NOT NULL,
  `NAME` VARCHAR(254) NOT NULL,
  `URL` VARCHAR(254) NOT NULL,
  `ALLOW_USER_SET` DECIMAL(3,0) DEFAULT NULL,
  `REQUIRES_CERTIFICATE` DECIMAL(3,0) DEFAULT NULL,
  `CHALLENGE_RESPONSE_AUTH` DECIMAL(3,0) DEFAULT NULL,
  `FORM_AUTH` DECIMAL(3,0) DEFAULT NULL,
  `FORM_USER_FIELD` VARCHAR(128) DEFAULT NULL,
  `FORM_PWD_FIELD` VARCHAR(128) DEFAULT NULL,
  `REALM` VARCHAR(128) DEFAULT NULL,
  `DOMAIN_ID` DECIMAL(65,30) NOT NULL,
  PRIMARY KEY (`SITE_ID`),
  UNIQUE KEY `UIX_SITE_NAME` (`NAME`) USING BTREE,
  UNIQUE KEY `UIX_SITE_URL` (`URL`) USING BTREE,
  KEY `IX_SECURITY_DOMAIN_2` (`DOMAIN_ID`) USING BTREE,
  CONSTRAINT `SSO_SITE_IBFK_1` FOREIGN KEY (`DOMAIN_ID`) REFERENCES `SECURITY_DOMAIN` (`DOMAIN_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
