SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR USER_ACTIVITY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `USER_ACTIVITY` (
  `ACTIVITY` VARCHAR(40) DEFAULT NULL,
  `CATEGORY` VARCHAR(40) DEFAULT NULL,
  `USER_NAME` VARCHAR(80) DEFAULT NULL,
  `TIME_STAMP` DATETIME DEFAULT NULL,
  `IPADDRESS` VARCHAR(80) DEFAULT NULL,
  `ATTR_NAME` VARCHAR(200) DEFAULT NULL,
  `ATTR_VALUE_BEFORE` TEXT,
  `ATTR_VALUE_AFTER` TEXT,
  `DESCRIPTION` VARCHAR(128) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
