#!/bin/bash
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_evt_log.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ge_bytearray.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ge_property.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_actinst.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_attachment.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_comment.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_detail.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_identitylink.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_procinst.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_taskinst.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_hi_varinst.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_id_group.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_id_info.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_id_membership.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_id_user.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_procdef_info.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_re_deployment.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_re_model.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_re_procdef.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_deadletter_job.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_event_subscr.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_execution.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_identitylink.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_job.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_suspended_job.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_task.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_timer_job.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/act_ru_variable.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_agency.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_bizdomain.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_bizdomain_value.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_brand_basic.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_brand_detail.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_car.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_car_owner.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_credential.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_customized_form.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_customized_form_mapping.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_customzied_form_values.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_daily_permission.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_department.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_documentations.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_gis_location.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_group.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_materials.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_materials_consume.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_materials_repository.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_permission.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_principal.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_principal_group.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_role.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_sequence.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_serial_number.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_services.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_services_daily.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_services_mapping.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_sso_session.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_staff.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_store_information.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_vip.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_wo.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_workflow_type.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_work_order_type.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_work_order_type_daily.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_wo_status.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_wo_status_value.sql
mysql -u$PMS_USER_NAME -p$PMS_PWD $PMS_DATABASE_NAME < $SCRIPT_ROOT_PATH/pms/create/pms_wo_status_value_daily.sql
