SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_ROLE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_ROLE` (
  `ID` DECIMAL(7,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `NAME` VARCHAR(25) NOT NULL,
  `STATUS` DECIMAL(1,0) NOT NULL,
  `CREATE_TIME` DATETIME NOT NULL,
  `DEPARTMENT_ID` DECIMAL(4,0) NOT NULL,
  `DESCRIPTION` VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `DEPARTMENT_ID` (`DEPARTMENT_ID`) USING BTREE,
  CONSTRAINT `PMS_ROLE_IBFK_1` FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `PMS_DEPARTMENT` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
