SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_CAR
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_CAR` (
  `ID` DECIMAL(8,0) NOT NULL,
  `CAR_NUMBER` VARCHAR(9) NOT NULL,
  `BRAND` VARCHAR(25) DEFAULT NULL,
  `MODEL` VARCHAR(25) DEFAULT NULL,
  `PUBLISH` DECIMAL(4,0) DEFAULT NULL,
  `OUTPUT_VOLUME` DECIMAL(2,1) DEFAULT NULL,
  `COLOR` VARCHAR(50) DEFAULT NULL,
  `MILEAGE` DECIMAL(8,0) DEFAULT NULL,
  `AGENCY` VARCHAR(25) DEFAULT NULL,
  `LOGO` VARCHAR(45) DEFAULT NULL,
  `NAME` VARCHAR(50) DEFAULT NULL,
  `INLET_FORM` VARCHAR(25) DEFAULT NULL,
  `GEARBOX` VARCHAR(25) DEFAULT NULL,
  `PICTURE` VARCHAR(45) DEFAULT NULL,
  `CAR_TYPE` TEXT,
  PRIMARY KEY (`ID`),
  KEY `INDEX_CAR_NUM` (`CAR_NUMBER`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
