SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_SEQUENCE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_SEQUENCE` (
  `TABLE_NAME` VARCHAR(50) NOT NULL,
  `MAX_VALUE` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`TABLE_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
