SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_WORKFLOW_TYPE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_WORKFLOW_TYPE` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `TYPE_NAME` VARCHAR(25) NOT NULL,
  `IS_ENABLE` DECIMAL(1,0) NOT NULL,
  `MASTER_PROCESS` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
