SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_CAR_OWNER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_CAR_OWNER` (
  `ID` DECIMAL(8,0) NOT NULL,
  `VIP_SERIAL_NUMBER` VARCHAR(50) DEFAULT NULL,
  `NAME` VARCHAR(25) NOT NULL,
  `SEX` DECIMAL(1,0) NOT NULL,
  `TEL` VARCHAR(14) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `HOME_ADDRESS` VARCHAR(80) DEFAULT NULL,
  `CAR_ID` DECIMAL(8,0) NOT NULL,
  `WORK_ORDER_ID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDEX_WORK_ORDER_ID` (`WORK_ORDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
