SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_WORK_ORDER_TYPE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_WORK_ORDER_TYPE` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `TYPE_NAME` VARCHAR(25) NOT NULL,
  `WO_STATUS_NAME` VARCHAR(25) DEFAULT NULL,
  `WORKFLOW_TYPE_NAME` VARCHAR(25) DEFAULT NULL,
  `IS_ENABLE` DECIMAL(1,0) NOT NULL,
  `CAR_OWNER_SECTION` DECIMAL(1,0) NOT NULL,
  `CAR_SECTION` DECIMAL(1,0) NOT NULL,
  `SERVICE_SECTION` DECIMAL(1,0) NOT NULL,
  `ONSITE_SERVICE_SECTION` DECIMAL(1,0) NOT NULL,
  `CUSTOMIZED_FORM_SECTION` DECIMAL(1,0) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
