SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_WO
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_WO` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `WORK_ORDER_ID` VARCHAR(50) NOT NULL,
  `WORK_ORDER_TYPE` VARCHAR(25) NOT NULL,
  `WORK_ORDER_STATUS` VARCHAR(50) DEFAULT NULL,
  `CREATED_TIME` DATETIME NOT NULL,
  `UPDATED_TIME` DATETIME DEFAULT NULL,
  `TOTAL_FEE` FLOAT DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDEX_WORK_ORDER_ID` (`WORK_ORDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
