SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_CUSTOMIZED_FORM
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_CUSTOMIZED_FORM` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `HTML` LONGTEXT,
  `NAME` VARCHAR(25) NOT NULL,
  `DESCRIPTION` VARCHAR(100) DEFAULT NULL,
  `STATUS` DECIMAL(1,0) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
