SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_WO_STATUS
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_WO_STATUS` (
  `AGENCY` VARCHAR(25) NOT NULL,
  `STATUS_NAME` VARCHAR(25) NOT NULL,
  `IS_ENABLE` DECIMAL(1,0) NOT NULL,
  PRIMARY KEY (`AGENCY`,`STATUS_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
