SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_CUSTOMZIED_FORM_VALUES
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_CUSTOMZIED_FORM_VALUES` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `CUSTOMIZED_FORM_VALUES` LONGTEXT,
  `KEY1` VARCHAR(25) NOT NULL,
  `KEY2` VARCHAR(25) DEFAULT NULL,
  `KEY3` VARCHAR(25) DEFAULT NULL,
  `CATEGORY` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDEX_KEY1` (`AGENCY`,`CATEGORY`,`KEY1`),
  KEY `INDEX_KEY2` (`AGENCY`,`CATEGORY`,`KEY1`,`KEY2`),
  KEY `INDEX_KEY3` (`AGENCY`,`CATEGORY`,`KEY1`,`KEY2`,`KEY3`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
