SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_BRAND_BASIC
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_BRAND_BASIC` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `CATEGORY` VARCHAR(25) NOT NULL,
  `BRAND` VARCHAR(25) DEFAULT NULL,
  `MODEL` VARCHAR(25) DEFAULT NULL,
  `PUBLISH` DECIMAL(4,0) DEFAULT NULL,
  `LEV` DECIMAL(1,0) NOT NULL,
  `LOGO` VARCHAR(45) DEFAULT NULL,
  `CAR_TYPE` TEXT,
  PRIMARY KEY (`ID`),
  KEY `INDEX_CATEGORY` (`AGENCY`,`CATEGORY`),
  KEY `INDEX_BRAND` (`AGENCY`,`CATEGORY`,`BRAND`),
  KEY `INDEX_MODEL` (`AGENCY`,`CATEGORY`,`BRAND`,`MODEL`),
  KEY `INDEX_PUBLISH` (`AGENCY`,`CATEGORY`,`BRAND`,`MODEL`,`PUBLISH`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
