SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_WO_STATUS_VALUE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_WO_STATUS_VALUE` (
  `AGENCY` VARCHAR(25) NOT NULL,
  `STATUS_NAME` VARCHAR(25) NOT NULL,
  `VALUE_NAME` VARCHAR(50) NOT NULL,
  `IS_ENABLE` DECIMAL(1,0) NOT NULL,
  PRIMARY KEY (`AGENCY`,`STATUS_NAME`,`VALUE_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
