SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_WO_STATUS_VALUE_DAILY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_WO_STATUS_VALUE_DAILY` (
  `AGENCY` VARCHAR(25) NOT NULL,
  `STATUS_NAME` VARCHAR(25) NOT NULL,
  `VALUE_NAME` VARCHAR(50) NOT NULL,
  `WORK_ORDER_ID` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`AGENCY`,`STATUS_NAME`,`VALUE_NAME`),
  KEY `INDEX_WORK_ORDER_ID` (`WORK_ORDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
