SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_DAILY_PERMISSION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_DAILY_PERMISSION` (
  `REFERENCE_ID` DECIMAL(7,0) NOT NULL,
  `FID` DECIMAL(7,0) NOT NULL,
  `OPERATION` DECIMAL(1,0) NOT NULL,
  `USER_LEVEL` DECIMAL(1,0) NOT NULL,
  KEY `FID` (`FID`) USING BTREE,
  CONSTRAINT `PMS_DAILY_PERMISSION_IBFK_1` FOREIGN KEY (`FID`) REFERENCES `PMS_PERMISSION` (`FID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
