SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_BRAND_DETAIL
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_BRAND_DETAIL` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `BRAND_BASIC_ID` DECIMAL(8,0) DEFAULT NULL,
  `NAME` VARCHAR(50) NOT NULL,
  `COLORS` TEXT NOT NULL,
  `OUTPUT_VOLUME` DECIMAL(2,1) NOT NULL,
  `INLET_FORM` VARCHAR(25) NOT NULL,
  `GEARBOX` VARCHAR(25) NOT NULL,
  `PICTURES` LONGTEXT,
  PRIMARY KEY (`ID`),
  KEY `BRAND_BASIC_ID` (`BRAND_BASIC_ID`) USING BTREE,
  CONSTRAINT `PMS_BRAND_DETAIL_IBFK_1` FOREIGN KEY (`BRAND_BASIC_ID`) REFERENCES `PMS_BRAND_BASIC` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
