SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_STAFF
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_STAFF` (
  `ID` DECIMAL(7,0) NOT NULL,
  `SEX` DECIMAL(1,0) NOT NULL,
  `FNAME` VARCHAR(20) NOT NULL,
  `MNAME` VARCHAR(20) DEFAULT NULL,
  `LNAME` VARCHAR(20) NOT NULL,
  `TEL` VARCHAR(15) DEFAULT NULL,
  `PIN` VARCHAR(20) NOT NULL,
  `SSN` VARCHAR(20) DEFAULT NULL,
  `RHF` VARCHAR(20) DEFAULT NULL,
  `CURRENT_ADDRESS` VARCHAR(100) NOT NULL,
  `COUNTRY` VARCHAR(50) NOT NULL,
  `SCHOOL` VARCHAR(50) DEFAULT NULL,
  `MAJOR` VARCHAR(50) DEFAULT NULL,
  `BIRTHDAY` DATETIME NOT NULL,
  `CENSUS_REGISTER` VARCHAR(20) NOT NULL,
  `CENSUS_ADDRESS` VARCHAR(100) NOT NULL,
  `HIREDATE` DATETIME NOT NULL,
  `NATIONALITY` VARCHAR(40) NOT NULL,
  `CREATE_TIME` DATETIME NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `EDUCATION_DEGREE` VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
