SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_MATERIALS_REPOSITORY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_MATERIALS_REPOSITORY` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `SERIAL_NUMBER` VARCHAR(50) NOT NULL,
  `MATERIAL_NAME` VARCHAR(25) NOT NULL,
  `DISPLAY_NAME` VARCHAR(100) DEFAULT NULL,
  `MATERIAL_BRAND` VARCHAR(25) NOT NULL,
  `MATERIAL_TYPE` VARCHAR(25) NOT NULL,
  `MATERIAL_ICON` VARCHAR(45) DEFAULT NULL,
  `PURCHASE_PRICE` DECIMAL(7,2) NOT NULL,
  `SALE_PRICE` DECIMAL(7,2) NOT NULL,
  `PRODUCTION_DATE` DATETIME NOT NULL,
  `EXPIRATION_DATE` DATETIME DEFAULT NULL,
  `PURCHASE_DATE` DATETIME NOT NULL,
  `SALED_AMOUNT` DECIMAL(5,0) DEFAULT '0',
  `PURCHASE_AMOUNT` DECIMAL(5,0) NOT NULL,
  `MATERIAL_UNIT` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDEX_SERIAL_NUMBER` (`SERIAL_NUMBER`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
