SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_VIP
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_VIP` (
  `ID` DECIMAL(8,0) NOT NULL,
  `SERIAL_NUMBER` VARCHAR(50) NOT NULL,
  `NAME` VARCHAR(25) NOT NULL,
  `SEX` DECIMAL(1,0) NOT NULL,
  `TEL` VARCHAR(14) NOT NULL,
  `EMAIL` VARCHAR(50) DEFAULT NULL,
  `CAR_NUMBER` VARCHAR(9) NOT NULL,
  `REGISTER_DATE` DATETIME NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `HOME_ADDRESS` VARCHAR(80) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDEX_SERIAL_NUM` (`SERIAL_NUMBER`),
  KEY `INDEX_CAR_NUM` (`CAR_NUMBER`),
  KEY `INDEX_TEL` (`TEL`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
