SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_SSO_SESSION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_SSO_SESSION` (
  `SESSION_ID` VARCHAR(50) NOT NULL,
  `TOKEN` VARCHAR(50) NOT NULL,
  `TIME_OUT` DECIMAL(20,0) NOT NULL,
  `START_ACCESS_TIME` DATETIME NOT NULL,
  `LAST_ACCESS_TIME` DATETIME NOT NULL,
  `HOST_NAME` VARCHAR(15) NOT NULL,
  `SESSION_OBJECT` LONGBLOB,
  `AGENCY` VARCHAR(25) NOT NULL,
  `LOGIN_NAME` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`SESSION_ID`),
  KEY `INDEX_TOKEN` (`TOKEN`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
