SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_WORK_ORDER_TYPE_DAILY
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_WORK_ORDER_TYPE_DAILY` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `TYPE_NAME` VARCHAR(25) NOT NULL,
  `WO_STATUS_NAME` VARCHAR(25) DEFAULT NULL,
  `WORKFLOW_TYPE_NAME` VARCHAR(25) DEFAULT NULL,
  `WORK_ORDER_ID` VARCHAR(50) NOT NULL,
  `CAR_OWNER_SECTION` DECIMAL(1,0) NOT NULL,
  `CAR_SECTION` DECIMAL(1,0) NOT NULL,
  `SERVICE_SECTION` DECIMAL(1,0) NOT NULL,
  `ONSITE_SERVICE_SECTION` DECIMAL(1,0) NOT NULL,
  `CUSTOMIZED_FORM_SECTION` DECIMAL(1,0) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `INDEX_WORK_ORDER_ID` (`WORK_ORDER_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
