SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_BIZDOMAIN_VALUE
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_BIZDOMAIN_VALUE` (
  `ID` DECIMAL(7,0) NOT NULL COMMENT 'STANDARD CHOICE VALUE PRIMARY',
  `AGENCY` VARCHAR(25) NOT NULL COMMENT 'AGENCY NAME',
  `BIZDOMAIN` VARCHAR(50) NOT NULL COMMENT 'STANDARD CHOICE NAME',
  `BIZDOMAIN_VALUE` VARCHAR(50) NOT NULL,
  `CREATE_TIME` DATETIME NOT NULL COMMENT 'STANDARD CHOICE VALUE CREATE DATE',
  `FULL_NAME` VARCHAR(25) NOT NULL COMMENT 'STANDARD CHOICE VALUE UPDATE BY',
  `STATUS` DECIMAL(1,0) DEFAULT NULL COMMENT 'STANDARD CHOICE VALUE STATUS',
  `VALUE_DESC` TEXT COMMENT 'STANDARD CHOICE VALUE DESCRIPTION',
  PRIMARY KEY (`ID`),
  KEY `INDEX_BIZ_DOMAIN` (`BIZDOMAIN`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='STANDARD CHOICE VALUE';
