SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_CREDENTIAL
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_CREDENTIAL` (
  `AGENCY` VARCHAR(25) NOT NULL,
  `LOGIN_NAME` VARCHAR(25) NOT NULL,
  `PASSWORD` VARCHAR(60) NOT NULL,
  `CHANGE_NEXT_LOGIN` DECIMAL(1,0) DEFAULT NULL,
  `EXPIRE_DATE` DATETIME DEFAULT NULL,
  `UPDATE_DATE` DATETIME DEFAULT NULL,
  PRIMARY KEY (`AGENCY`,`LOGIN_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
