SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_BIZDOMAIN
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_BIZDOMAIN` (
  `ID` DECIMAL(7,0) NOT NULL COMMENT 'STANDARD CHOICE PRIMARY',
  `AGENCY` VARCHAR(25) NOT NULL COMMENT 'AGENCY NAME',
  `BIZDOMAIN` VARCHAR(50) NOT NULL COMMENT 'STANDARD CHOICE NAME',
  `DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT 'STANDARD CHOICE DESCRIPTION',
  `CREATE_TIME` DATETIME NOT NULL COMMENT 'STANDARD CHOICE CREATE DATE',
  `FUL_NAME` VARCHAR(70) NOT NULL COMMENT 'STANDARD CHOICE UPDATE BY',
  `STATUS` VARCHAR(1) DEFAULT NULL COMMENT 'STANDARD CHOICE STATUS',
  PRIMARY KEY (`ID`),
  KEY `INDEX_BIZ_DOMAIN` (`BIZDOMAIN`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='STANDARD CHOICE';
