SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_MATERIALS_CONSUME
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_MATERIALS_CONSUME` (
  `SERVICE_DAILY_ID` DECIMAL(8,0) NOT NULL,
  `WORK_ORDER_ID` VARCHAR(50) NOT NULL,
  `MATERIAL_REPOSITORY_ID` DECIMAL(8,0) DEFAULT NULL,
  `CONSUMED_AMOUNT` DECIMAL(3,0) NOT NULL,
  `MATERIAL_ID` DECIMAL(8,0) DEFAULT NULL,
  KEY `INDEX_MATERIAL_CONSUME_REPOSITORY_ID` (`MATERIAL_REPOSITORY_ID`) USING BTREE,
  KEY `INDEX_MATERIAL_CONSUME_WORK_ORDER_ID` (`WORK_ORDER_ID`) USING BTREE,
  KEY `INDEX_MATERIAL_CONSUME_MATERIAL_ID` (`MATERIAL_ID`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
