SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_GIS_LOCATION
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_GIS_LOCATION` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `LOCATION_CATEGORY` VARCHAR(25) NOT NULL,
  `LOCATION_TYPE` VARCHAR(25) NOT NULL,
  `LOCATION_NAME` VARCHAR(100) NOT NULL,
  `KEY1` VARCHAR(25) NOT NULL,
  `KEY2` VARCHAR(25) DEFAULT NULL,
  `KEY3` VARCHAR(25) DEFAULT NULL,
  `COORDINATE_X` DOUBLE NOT NULL,
  `COORDINATE_Y` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `COMPLEX_INDEX_KEY1` (`AGENCY`,`LOCATION_CATEGORY`,`LOCATION_TYPE`,`KEY1`) USING BTREE,
  KEY `COMPLEX_INDEX_KEY2` (`AGENCY`,`LOCATION_CATEGORY`,`LOCATION_TYPE`,`KEY1`,`KEY2`),
  KEY `COMPLEX_INDEX_KEY3` (`AGENCY`,`LOCATION_CATEGORY`,`LOCATION_TYPE`,`KEY1`,`KEY2`,`KEY3`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
