SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_SERVICES
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_SERVICES` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `SERVICE_NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(100) DEFAULT NULL,
  `IS_ENABLE` DECIMAL(1,0) DEFAULT NULL,
  `SERVICE_PRICE` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
