SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_SERIAL_NUMBER
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_SERIAL_NUMBER` (
  `ID` DECIMAL(8,0) NOT NULL,
  `AGENCY` VARCHAR(25) NOT NULL,
  `CATEGORY` VARCHAR(25) DEFAULT NULL,
  `TYPE` DECIMAL(1,0) DEFAULT NULL,
  `LENGTH` DECIMAL(2,0) DEFAULT NULL,
  `SEQUENCE` DECIMAL(2,0) DEFAULT NULL,
  `VALUE` VARCHAR(25) DEFAULT NULL,
  `PARENT_ID` DECIMAL(8,0) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `PMS_SERIAL_NUMBER_INDEX1` (`PARENT_ID`),
  CONSTRAINT `PMS_SERIAL_NUMBER_IBFK_1` FOREIGN KEY (`PARENT_ID`) REFERENCES `PMS_SERIAL_NUMBER` (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
