SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- TABLE STRUCTURE FOR PMS_SERVICES_MAPPING
-- ----------------------------
CREATE TABLE IF NOT EXISTS `PMS_SERVICES_MAPPING` (
  `BRAND_BASIC_ID` DECIMAL(8,0) DEFAULT '0',
  `SERVICE_ID` DECIMAL(8,0) DEFAULT NULL,
  `MATERIAL_ID` DECIMAL(8,0) DEFAULT NULL,
  `AGENCY` VARCHAR(25) DEFAULT NULL,
  `BRAND_DETAIL_ID` DECIMAL(8,0) DEFAULT NULL,
  `MATERIAL_AMOUNT` DECIMAL(3,0) DEFAULT NULL,
  UNIQUE KEY `SERVICE_ID_2` (`SERVICE_ID`,`MATERIAL_ID`,`BRAND_BASIC_ID`),
  UNIQUE KEY `SERVICE_ID_3` (`SERVICE_ID`,`MATERIAL_ID`,`BRAND_DETAIL_ID`),
  KEY `SERVICE_ID` (`SERVICE_ID`) USING BTREE,
  KEY `MATERIAL_ID` (`MATERIAL_ID`) USING BTREE,
  KEY `PMS_SERVICES_MAPPING_IBFK_4` (`BRAND_DETAIL_ID`),
  KEY `PMS_SERVICES_MAPPING_IBFK_1` (`BRAND_BASIC_ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
